# The services of the project.
#
# Each service listed will be deployed to power your project.

db:
    type: oracle-mysql:8.0
    disk: 1024
search:
    type: elasticsearch:7.9 # should actually be 8.4 at minimum but elasticsearch license doesn't allow us to do this yet
    disk: 512
jobs:
    type: network-storage:1.0
    disk: 128
